### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [SergDi/kottans-js-2016#4]
`let classes = ['form-group', 'form-control', 'col-lg-4'];` - можно заюзать const. Также, частой практикой является называть константы в UPPERCASE_STYLE по соглашению. Проще визуально понимать.
`classes.some(s => s === current)` -> `classes.contains(s)`

Логика в редюсе делает 2 вещи, и тут нужно понимать – иногда нужно, чтобы работало чуток быстрее и делать так, иногда лучше сделать более читаемо и сделать два вызова к отдельным кускам (по сути, одна часть высчитываеть кастомные аттрибуты на основании классов, другая - делает фильтр классов).

`if (customAttrs)` – поскольку по умолчанию он равен `{}`, а это значение при приведении к Boolean дает тру, то эта логика будет выполняться всегда

При присвоении чего-то в customAttrs лучше присваивать конкретному ключу, а не всему объекту - вдруг при изменении требований тебе придется еще что-то дописывать/переписывать в том же редюсе

```
customAttrs['data-js'] = customAttrs['data-js'] !== undefined ? 
        ? customAttrs['data-js'] + ' ' + current.substr(3)
        : current.substr(3)
```

Тут так можно было бы поизголяться над формой задания этого и сделать что-то в духе

```
[customAttrs['data-js'] || '', current.substr(3)].join(' ').trim()
```

or

```
[customAttrs['data-js'] || '', current.substr(3)].filter(i => i).join(' ')
```

Опять же, для того, чтобы было короче/легче для восприятия – чуток вкусовщины.

```
if (!(classes.some(s => s === current) || current.substr(0, 3) === 'js-'))
    return prev === null
        ? current
        : prev + ' ' + current
else
    return prev
```

В общем и целом `if (a) return x else return y` можно смело сокращать до
`if (a) return x
return y
`
Про такие всякие штуки можно почитать у Martin Fowler 'Refactoring: Improving the Design of Existing Code'

**Comment by shvaikalesh** [comment]
> `classes.contains(s)`

`classes` is regular `Array`, so use `includes`

> `current.substr(0, 3) === 'js-'`

`current.startsWith('js-')`

> `customAttrs['data-js'] !== undefined`

`'data-js' in customAttrs`

And yeah, split `data-js` and classes removal logic to different reducers and compose them.

**Comment by SergDi** [comment]
рекомендации учтены и заимплименчены

**Comment by shvaikalesh** [comment]
don't do `!!` with `ifs` or other stuff that does `ToBoolean`

`substr` => `slice`
`substr` is Annex B, thus deprecated
